egg_text = """
................
................
................
......eeee......
.....eEEEEe.....
....eEEEEEWe....
...eEEEEEEEEe...
...eEEEEEEEEe...
...eEEEEEEEEe...
...eEEEEEEEEe...
...eEEEEEEEEe...
....eEEEEEEe....
.....eeeeee.....
................
................
................
"""

dragon_text = """
................
........dd......
.......dDDd.....
.......dDDd.d...
......dDDDDddd..
.d..dDDDDDDDDDd.
.dd.dDDDDDDdDd..
.dDddDDDDDDdDd..
.dDDdDDDDDDddd..
..dDDDDDDDDd....
...dDDDDDDd.....
...dDd..dDd.....
...dd....dd.....
................
................
................
"""

egg_palette = {
    'e': (180, 150, 100, 255),
    'E': (230, 210, 180, 255),
    'W': (255, 255, 255, 255)
}

dragon_palette = {
    'd': (30, 100, 30, 255),
    'D': (60, 180, 60, 255),
    'W': (255, 255, 255, 255)
}

def print_svg(name, text, palette):
    print(f"\n<!-- {name} SVG -->")
    print('<svg width="128" height="128" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg">')
    lines = text.strip().split('\n')
    for y, line in enumerate(lines):
        line = line.replace(' ', '')
        for x, char in enumerate(line):
            if char in palette:
                r, g, b, _ = palette[char]
                print(f'  <rect x="{x}" y="{y}" width="1" height="1" fill="rgb({r},{g},{b})" />')
    print('</svg>')

def print_c_array(name, text, palette):
    print(f"\nCOLORREF {name}[16][16] = {{")
    lines = text.strip().split('\n')
    for y, line in enumerate(lines):
        line = line.replace(' ', '')
        row = []
        for x, char in enumerate(line):
            if char in palette:
                r, g, b, _ = palette[char]
                row.append(f"RGB({r},{g},{b})")
            else:
                row.append("-1")
        print("    {" + ", ".join(row) + "},")
    print("};")

print_svg("Egg", egg_text, egg_palette)
print_svg("Dragon", dragon_text, dragon_palette)
print_c_array("egg_pixels", egg_text, egg_palette)
print_c_array("dragon_pixels", dragon_text, dragon_palette)
